name: Build Android APK
on:
  workflow_dispatch:
jobs:
  build-apk:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install Buildozer and dependencies
        run: |
          python -m pip install --upgrade pip
          pip install buildozer cython virtualenv
          sudo apt-get update
          sudo apt-get install -y libssl-dev libffi-dev libreadline-dev zlib1g-dev libncurses5-dev libsqlite3-dev openjdk-11-jdk unzip git
      - name: Build APK
        run: buildozer -v android debug
        timeout-minutes: 60
      - uses: actions/upload-artifact@v4
        with:
          name: gst_purchase_apk
          path: bin/*.apk
